name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: go mod download

      - name: Run linters
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
          $(go env GOPATH)/bin/golangci-lint run ./...
